### ISSUE TITLE
Code analysis for Software Security Engineering (Due Dec 9th)

### ISSUE THREAD

**Issue by Lord-Tiger** [Lord-Tiger/CYBR8420_Fall24#16]

**Comment by Lord-Tiger** [comment]
I just forked the OpenEMR official repository into this "https://github.com/Lord-Tiger/CYBR8420_Fall24-openemr" so that we can run scans on.

**Comment by Lord-Tiger** [comment]
SonarCloud scan results:
https://sonarcloud.io/summary/overall?id=Lord-Tiger_CYBR8420_Fall24-openemr&branch=master

**Comment by Lord-Tiger** [comment]
GitHub's CodeQL:
https://github.com/Lord-Tiger/CYBR8420_Fall24-openemr/security/code-scanning

**Comment by asongne** [comment]
Code Review Strategy:
The program we are looking at has different parts and our strategy is to perform a manual analysis on parts of the code such as login, authorization and Admin ACL as well as conducting an automated code analysis on the whole repository using Sonarcloud. We are using AI to understand the code and to suggest best practices in producing secure code. 
We used the following CWEs as the checklist to analyze our code:
CWE-20: Improper Input Validation 
CWE-116: Improper Encoding or Escaping of Output 
CWE-352: Cross-Site Request Forgery (CSRF) 
CWE-798: Use of Hardcoded Credentials 
CWE-285: Improper Authorization 
CWE-311: Missing Encryption of Sensitive Data
Manual Code Review
CWE-89: SQL Injection
1. SQL Injection Risk
Issue: 
The SQL queries use sqlStatement but do not clearly demonstrate parameterized queries. The following code taken from 63-64 of OpenEMRs login code shows a good security implementation. However, it is important to ensure all such queries are parameterized throughout the codebase.
$sql = "SELECT option_id, title,is_default FROM list_options WHERE list_id=? and activity=1 ORDER BY seq, option_id";
$rs = sqlStatement($sql, ['apps']);
Mitigation: Validate that all SQL queries across the platform use parameterized queries. Always sanitize input when constructing queries dynamically.

2. CWE-79: Improper Neutralization of Input During Web Page Generation ('XSS')
Issue: 
On line 87-88 of the login code, User-provided input like $_REQUEST['app'] is being processed and used to generate HTML, which might lead to XSS if attr() and other sanitization functions are insufficient or not uniformly applied:
$div_app = sprintf('<input type="hidden" name="appChoice" value="%s">', attr($_REQUEST['app']));
Mitigation: The developers must ensure all inputs are sanitized using robust methods like htmlspecialchars() or equivalent.
Apply output encoding consistently when rendering HTML, especially for dynamic inputs.

3. CWE-285: Improper Authorization
Issue: Starting on line 32 of the authorization script of OpenEMR
Authorization checks ($imauthorized) depend on $_SESSION['userauthorized'] and $see_auth values, which might not fully reflect user roles or permissions.
Example: $see_auth > 2 might grant excessive privileges.
Mitigation:
Implement stricter role-based access control (RBAC).
Validate session values like $_SESSION['userauthorized'] rigorously.

CWE-352: Cross-Site Request Forgery (CSRF)
Issue:
CSRF protection is implemented via CsrfUtils::verifyCsrfToken(), but not consistently:
Only the authorize action ($_GET["mode"] == "authorize") checks the CSRF token.
Other actions and AJAX calls do not validate CSRF tokens.
Mitigation:
Enforce CSRF validation on all state-changing requests.
Use secure and hidden CSRF tokens consistently

**Comment by asongne** [comment]
Reflection:

For this project, our group faced more challenges than usual since none of us have a background in coding. After meeting with the professor, we received valuable guidance on how to approach the task. Our objective was to scan the entire repository, map it to relevant CWE categories, and reflect on our findings. Initially, we struggled with dividing responsibilities among team members.

To tackle this, we relied on AI and referred to our previously submitted assignments. One team member conducted the static code analysis with the assistance of AI, while the automated analysis was performed by forking the repository into our GitHub and running a scan using SonarCloud. Given our limited coding expertise, AI proved to be an invaluable tool throughout the process.

The most significant challenge we faced was mapping our findings to the appropriate CWE categories, particularly with the list we had compiled. Aside from this, we did not uncover many issues, as it seems the developers had addressed most vulnerabilities prior to production—at least, that was our assumption based on the results.
